[package]
name = "mysql-format"
version = "0.1.0"
authors = ["Brian Leishman <brian@stumpyinc.com>"]

[dependencies]
time = "0.1.40"
# htmlescape = "*"
phf = "0.7.23"
# lazy_static = "1.2.0"
# regex = "1.0.6"

[build-dependencies] 
phf_codegen = "0.7.23"