[package]
name = "mysql-format"
version = "0.1.1"
authors = ["Brian Leishman <brian@stumpyinc.com>"]

[dependencies]
time = "0.1"
phf = "0.7"
actix-web = "1.0.7"

serde = "1.0.101"
serde_derive = "1.0.101"

[build-dependencies]
phf_codegen = "0.7"